title: Product
icon: book
options:
  changeSlug: true
  changeStatus: true
  changeTemplate: false
  changeTitle: true
  delete: true
  duplicate: true
  preview: true
  read: true
  update: true

status:
  draft:
    label: Draft
    text: This product is in draft mode and only visible for logged in editors or via secret link
  unlisted:
    label: Unlisted
    text: This product will not be shown anywhere on the site except on the Allergens page
  listed:
    label: Published
    text: This product is fully visible across the site


tabs:
  #
  #  Content Tab
  #
  content:
    label: Content
    columns:
      - width: 1/3
        sticky: true
        sections:
          #
          #  Files
          #
          files:
            type: files
            image:
              back: black
              cover: true

      - width: 2/3
        sections:
          content:
            type: fields
            fields:
              #
              #  Menu Image
              #
              menu_image:
                label: Menu Image
                type: files
                multiple: false
                layout: cards
                size: huge
                width: 1/3
                image:
                  back: white
                  cover: false
                  ratio: 1/1
                help: |
                  This should be on a transparent background.

              #
              #  Secondary Categories
              #
              secondary_categories:
                label: Secondary Categories
                type: pages
                multiple: true
                query: site.index.template('menu_category').listed
                subpages: false
                layout: list
                empty: No secondary categories selected.
                width: 2/3
                help: |
                  If you also want {{ page.title }} to appear under a different menu category, add it here.

              #
              #  Hero Image
              #
              hero_image_line:
                type: line

              hero_image:
                label: Hero Image
                type: files
                multiple: false
                layout: cards
                size: huge
                width: 1/3
                image:
                  back: white
                  cover: true
                  ratio: 3/2
                help: |
                  Used at the top of the {{ page.title }} page

              #
              #  Tag
              #  The value is stored as "{text},{color}"
              #
              tag:
                label: Tag
                type: select
                options:
                  - value: beef,red
                    text: Beef
                  - value: booze,orange
                    text: Booze
                  - value: chicken,blue
                    text: Chicken
                  - value: vegetarian,green
                    text: Vegetarian
                  - value: vegan,green
                    text: Vegan

              #
              #  Description
              #
              description:
                label: Description
                type: writer
                marks:
                  - bold
                  - italic
                  - underline
                  - strike
                  - link
                nodes:
                  - bulletList
                  - orderedList
                  - listItem

              #
              #  Allergens
              #
              allergens_headline:
                label: Allergens
                type: headline
                numbered: false
                help: |
                  New ingredients and allergens can be created on the <a href="{{ site.index.find('Allergens').panelUrl }}">Allergens page</a>. They can then be added here.

              ingredients:
                label: Ingredients this product contains
                type: pages
                query: site.index.template('ingredient')
                subpages: false
                empty: This product has no ingredients.
                help: |
                  Select *all* the ingredients that this product contains.
                  Allergens and dietary preferences associated with these ingredients can then be pulled in automatically.

              preparation_allergens:
                label: Preparation allergens
                type: pages
                query: site.index.template('allergen')
                subpages: false
                empty: This product has preparation allergens.
                help: |
                  Select *all* the allergens that this product may come into contact with duration preparation.

              #
              #  Stories
              #
              stories:
                extends: fields/stories
                fields:
                  stories:
                    image:
                      query: page.regular_media.toFile
                      cover: false
                      ratio: 1/1
                    info: "{{ page.description.excerpt(60) }}"

              #
              #  Footer Illustration
              #
              footer_illustration_line:
                type: line

              footer_illustration:
                extends: fields/footer_illustration

  #
  #  SEO Tab
  #
  seo:
    extends: tabs/seo
