title: Site

options:
  changeTitle: false

tabs:
  #
  #  Pages
  #
  pages:
    label: Pages
    columns:
      - width: 1/2
        sections:
          #
          #  Campaigns
          #
          campaigns:
            headline: Campaigns
            type: pages
            create: campaign
            template: campaign
            empty: No campaigns yet

          #
          #  Blog Posts
          #
          blog_posts:
            headline: Blog Posts
            type: pages
            create: post
            parent: site.children.template('blog').first
            templates:
              - post

          #
          #  Quick Redirects
          #
          quick_redirects:
            headline: Quick Redirects
            type: pages
            create: redirect
            templates:
              - redirect

      - width: 1/2
        sections:

          #
          #  Main Pages
          #
          main_pages:
            headline: Main Pages
            type: pages
            info: " {{ page.template }}"
            create: false
            templates:
              - home
              - menu
              - book
              - order
              - locations
              - blog
              - club

          #
          #  Pages
          #
          other_pages:
            headline: Other Pages
            type: pages
            info: " {{ page.template }}"
            create:
              - default
            templates:
              - default
              - allergens
              - error

  #
  #  Social Media
  #
  social:
    label: Social Media
    columns:
      - width: 1/1
        sections:
          social:
            type: fields
            fields:
              twitter:
                type: text
                label: Twitter Username
                icon: twitter
                width: 1/3
                placeholder: Username
                before: "@"

              facebook:
                type: url
                label: Facebook URL
                icon: facebook
                width: 1/3

              instagram:
                type: url
                label: Instagram URL
                icon: instagram
                width: 1/3

  #
  #  Header
  #
  header:
    label: Header
    columns:
      - width: 1/1
        sections:
          header:
            type: fields
            fields:
              header_menu:
                extends: fields/menu
                label: Menu

  #
  #  Footer
  #
  footer:
    label: Footer
    columns:
      - width: 1/1
        sections:
          footer:
            type: fields
            fields:
              footer_primary_menu:
                extends: fields/menu
                label: Primary Menu

              footer_secondary_menu:
                extends: fields/menu
                label: Secondary Menu

              copyright_text:
                label: Copyright Text
                type: text
                before: ©
                placeholder: Famously Proper Ltd.
                help: The current year will be added after this automatically

  #
  #  Stories
  #
  stories:
    label: Stories
    columns:
      - width: 1/1
        sections:
          stories:
            extends: sections/stories

  #
  #  Pop-Up
  #
  pop-up:
    label: Pop-up
    columns:
      - width: 1/3
        sticky: true
        sections:
          #
          #  Files
          #
          files:
            type: files
            width: 1/2
            image:
              back: black
              cover: true

      - width: 2/3
        sections:
          pop-up:
            type: fields
            fields:
              pop_up_toggle:
                label: Include?
                type: toggle
                width: 1/3
                default: false
                text:
                  - "No"
                  - "Yes"

              pop_up_spacer:
                type: gap
                width: 2/3

              pop_up_delay_in_seconds:
                label: Delay Before Showing
                type: number
                after: 'seconds'
                default: 5
                step: 0.5
                width: 1/3
                when:
                  pop_up_toggle: true

              pop_up_title:
                label: Title
                type: text
                when:
                  pop_up_toggle: true

              pop_up_text:
                label: Text
                type: writer
                marks:
                  - bold
                  - italic
                  - underline
                  - strike
                  - link
                nodes:
                  - bulletList
                  - orderedList
                  - listItem
                when:
                  pop_up_toggle: true

              pop_up_link_type:
                type: select
                label: Link Type
                width: 1/3
                options:
                  page: Page
                  url: URL
                default: page
                help: |
                  Select 'URL' for external sites
                when:
                  pop_up_toggle: true

              pop_up_link_text:
                type: text
                label: Link Text
                width: 1/3
                when:
                  pop_up_toggle: true

              pop_up_link_page:
                type: pages
                label: Page
                multiple: false
                width: 1/3
                when:
                  pop_up_link_type: page
                  pop_up_toggle: true

              pop_up_link_url:
                type: url
                label: URL
                width: 1/3
                when:
                  pop_up_link_type: url
                  pop_up_toggle: true

              pop_up_media_type:
                type: select
                label: Image Type
                width: 1/3
                options:
                  image: Image
                  animation: Animated Illustration
                default: image
                when:
                  pop_up_toggle: true

              pop_up_image:
                label: Image
                type: files
                multiple: false
                width: 2/3
                image:
                  back: black
                  cover: true
                when:
                  pop_up_toggle: true
                  pop_up_media_type: image

              pop_up_illustration:
                type: files
                label: Illustration
                multiple: false
                query: site.code
                width: 2/3
                help: |
                  This should be a JSON file that has been exported to work with <a href="https://airbnb.io/lottie/#/web">Lottie</a>.
                when:
                  pop_up_toggle: true
                  pop_up_media_type: animation

  #
  #  SEO Tab
  #
  seo:
    extends: tabs/seo
    label: SEO (fallbacks)
